version: "3.7"

services:
  artinfo-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myfolder/src
      - ./pages:/myfolder/pages
      - ./public:/myfolder/public
    ports:
      - 3001:3000
